<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Output defaults</name>
  <uuid>73bfa42a-eb20-4f4a-ab89-0226081c4bbf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ApprovalDecision where
		approved is true , 
		the messages are an empty list of strings ,
		the overallResult is "Approval default is true unless any failure rules trigger" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
