<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>589295ac-0455-4289-b4f7-009e3be08acc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set theApplication to a new Application where
		the loanAmount is 100000, 
		the loanToValuePercentage is 70, 
		the mortgageType is "FixedRate100", 
		the ID is "101", 
		the propertyValue is 150000 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
